export const CATEGORIES_MOCK = [
  {
    "category_id": 34,
    "parent_id": 0,
    "id_path": "phu-kien",
    "level": 1,
    "company_id": 1,
    "usergroup_ids": "3,4,5",
    "status": "A",
    "product_count": 25,
    "position": 0,
    "is_op": "N",
    "localization": "vn",
    "age_verification": "N",
    "age_limit": 0,
    "parent_age_verification": "N",
    "parent_age_limit": 0,
    "selected_views": "wuqioyeuiwqyeuiwq",
    "default_view": "",
    "product_details_view": "",
    "product_columns": 0,
    "is_trash": "N",
    "category_type": "C",
    "created_at": "2022-02-07 13:37:29",
    "updated_at": "2022-02-07 22:29:56",
    "category_description_id": 8,
    "lang_code": "vn",
    "category": "Phụ kiện Đồ chơi công nghệ",
    "description": "Phụ kiện",
    "meta_keywords": "Phụ kiện",
    "meta_description": "Phụ kiện",
    "page_title": "Phụ kiện",
    "age_warning_message": "Warning message",
    "data": [
      {
        "category_id": 40,
        "parent_id": 34,
        "id_path": "phu-kien/cap-sac",
        "level": 2,
        "company_id": 0,
        "usergroup_ids": "23,24,25",
        "status": "A",
        "product_count": 200,
        "position": 0,
        "is_op": "N",
        "localization": "vn",
        "age_verification": "N",
        "age_limit": 0,
        "parent_age_verification": "N",
        "parent_age_limit": 0,
        "selected_views": "",
        "default_view": "",
        "product_details_view": "",
        "product_columns": 0,
        "is_trash": "N",
        "category_type": "C",
        "created_at": "2022-02-07 22:15:52",
        "updated_at": "2022-02-07 22:15:52",
        "category_description_id": 14,
        "lang_code": "vn",
        "category": "Cáp sạc",
        "description": "Phụ kiện cáp sạc",
        "meta_keywords": "Phụ kiện, cáp sạc",
        "meta_description": "Phụ kiện, cáp sạc",
        "page_title": "Phụ kiện cáp sạc",
        "age_warning_message": ""
      },
      {
        "category_id": 41,
        "parent_id": 34,
        "id_path": "phu-kien/tai-nghe",
        "level": 2,
        "company_id": 0,
        "usergroup_ids": "23,24,25",
        "status": "A",
        "product_count": 200,
        "position": 0,
        "is_op": "N",
        "localization": "vn",
        "age_verification": "N",
        "age_limit": 0,
        "parent_age_verification": "N",
        "parent_age_limit": 0,
        "selected_views": "",
        "default_view": "",
        "product_details_view": "",
        "product_columns": 0,
        "is_trash": "N",
        "category_type": "C",
        "created_at": "2022-02-07 22:16:25",
        "updated_at": "2022-02-07 22:32:22",
        "category_description_id": 15,
        "lang_code": "vn",
        "category": "Tai nghe",
        "description": "Phụ kiện Tai nghe",
        "meta_keywords": "Phụ kiện, Tai nghe",
        "meta_description": "Phụ kiện, Tai nghe",
        "page_title": "Phụ kiện Tai nghe",
        "age_warning_message": ""
      },
      {
        "category_id": 42,
        "parent_id": 34,
        "id_path": "phu-kien/loa",
        "level": 2,
        "company_id": 0,
        "usergroup_ids": "23,24,25",
        "status": "A",
        "product_count": 200,
        "position": 0,
        "is_op": "N",
        "localization": "vn",
        "age_verification": "N",
        "age_limit": 0,
        "parent_age_verification": "N",
        "parent_age_limit": 0,
        "selected_views": "",
        "default_view": "",
        "product_details_view": "",
        "product_columns": 0,
        "is_trash": "N",
        "category_type": "C",
        "created_at": "2022-02-07 22:16:52",
        "updated_at": "2022-02-07 22:32:34",
        "category_description_id": 16,
        "lang_code": "vn",
        "category": "Loa",
        "description": "Phụ kiện Loa",
        "meta_keywords": "Phụ kiện, Loa",
        "meta_description": "Phụ kiện, Loa",
        "page_title": "Phụ kiện Loa",
        "age_warning_message": ""
      }
    ]
  }
]
export const selectOptions = {
  name: 'name',
  value: 'value'
}

export const layout = {
  labelCol: { span: 5 },
  wrapperCol: { span: 19 },

};

export const tailLayout = {
  wrapperCol: { offset: 8, span: 16 },
};

export const dataOptions = [{ name: 'Hiển thị', value: 'A' }, { name: 'Ẩn', value: 'D' }];
export const dataProducts = [{ name: 'Thêm sản phẩm thủ công', value: 'Y' }, { name: 'Thêm sản phẩm tự động', value: 'N' }];
export const dataTypes = [{ name: 'Order', value: 'O' }, { name: 'Shipping', value: 'S' }];

export const columnsTest = [
  { title: 'key', dataIndex: 'key', key: 'key' },
  { title: 'Age', dataIndex: 'age', key: 'age' },
  { title: 'Address', dataIndex: 'address', key: 'address' }
];

export const dataTest={
  "statusCode": 200,
  "data": [
      {
          "category_id": 60,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 500,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:23:06",
          "display_at": "2022-02-13T11:23:06.000Z",
          "category_description_id": 31,
          "lang_code": "vn",
          "category": "Điện thoại",
          "description": "Điện thoại",
          "meta_keywords": "Bán lẻ điện thoại 5G chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Bán lẻ điện thoại 5G chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "page_title": "Điện thoại",
          "age_warning_message": "",
          "children": [
              {
                  "category_id": 61,
                  "parent_id": 60,
                  "id_path": "/60",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 500,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 18:25:02",
                  "display_at": "2022-02-13T11:25:02.000Z",
                  "category_description_id": 32,
                  "lang_code": "vn",
                  "category": "IPhone",
                  "description": "IPhone",
                  "meta_keywords": "Tag sản phẩm bằng IPhone, Tag sản phẩm bằng iphone 13",
                  "meta_description": "Điện thoại IPhone, IPhone 13",
                  "page_title": "Iphone",
                  "age_warning_message": ""
              },
              {
                  "category_id": 62,
                  "parent_id": 60,
                  "id_path": "/60",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 18:26:02",
                  "display_at": "2022-02-13T11:26:02.000Z",
                  "category_description_id": 33,
                  "lang_code": "vn",
                  "category": "Samsung",
                  "description": "Samsung",
                  "meta_keywords": "Tag sản phẩm bằng Samsung",
                  "meta_description": "Điện thoại Samsung",
                  "page_title": "Samsung",
                  "age_warning_message": ""
              },
              {
                  "category_id": 63,
                  "parent_id": 60,
                  "id_path": "/60",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 18:26:18",
                  "display_at": "2022-02-13T11:26:18.000Z",
                  "category_description_id": 34,
                  "lang_code": "vn",
                  "category": "Oppo",
                  "description": "Oppo",
                  "meta_keywords": "Tag sản phẩm bằng Oppo",
                  "meta_description": "Điện thoại Oppo",
                  "page_title": "Oppo",
                  "age_warning_message": ""
              },
              {
                  "category_id": 64,
                  "parent_id": 60,
                  "id_path": "/60",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 18:26:33",
                  "display_at": "2022-02-13T11:26:33.000Z",
                  "category_description_id": 35,
                  "lang_code": "vn",
                  "category": "Xiaomi",
                  "description": "Xiaomi",
                  "meta_keywords": "Tag sản phẩm bằng Xiaomi",
                  "meta_description": "Điện thoại Xiaomi",
                  "page_title": "Xiaomi",
                  "age_warning_message": ""
              },
              {
                  "category_id": 65,
                  "parent_id": 60,
                  "id_path": "/60",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 18:27:13",
                  "display_at": "2022-02-13T11:27:13.000Z",
                  "category_description_id": 36,
                  "lang_code": "vn",
                  "category": "Nokia",
                  "description": "Nokia",
                  "meta_keywords": "Tag sản phẩm bằng Nokia",
                  "meta_description": "Điện thoại Nokia",
                  "page_title": "Nokia",
                  "age_warning_message": ""
              }
            
          ]
      },
      {
          "category_id": 66,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 100,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:39:41",
          "display_at": "2022-02-13T11:39:41.000Z",
          "category_description_id": 37,
          "lang_code": "vn",
          "category": "Tablet",
          "description": "Tablet",
          "meta_keywords": "Bán lẻ Tablet chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Tablet",
          "page_title": "Tablet",
          "age_warning_message": "",
          "children": [
              {
                  "category_id": 71,
                  "parent_id": 66,
                  "id_path": "/66",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "A",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 20:45:44",
                  "display_at": "2022-03-10T00:00:00.000Z",
                  "category_description_id": 42,
                  "lang_code": "vn",
                  "category": "Ipad",
                  "description": "Ipad",
                  "meta_keywords": "Bán lẻ Ipad chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
                  "meta_description": "Ipad, Ipad Pro",
                  "page_title": "Ipad",
                  "age_warning_message": ""
              },
              {
                  "category_id": 72,
                  "parent_id": 66,
                  "id_path": "/66",
                  "level": 2,
                  "company_id": 0,
                  "usergroup_ids": "23",
                  "status": "D",
                  "product_count": 100,
                  "position": 0,
                  "is_op": "N",
                  "localization": "vn",
                  "age_verification": "N",
                  "age_limit": 0,
                  "parent_age_verification": "N",
                  "parent_age_limit": 0,
                  "selected_views": "",
                  "default_view": "",
                  "product_details_view": "",
                  "product_columns": 0,
                  "is_trash": "N",
                  "category_type": "C",
                  "created_at": "2022-02-13 20:55:03",
                  "display_at": "2022-05-31T00:00:00.000Z",
                  "category_description_id": 43,
                  "lang_code": "vn",
                  "category": "Samsung Note",
                  "description": "Samsung Note",
                  "meta_keywords": "Bán lẻ Samsung Note chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
                  "meta_description": "Samsung Note",
                  "page_title": "Samsung Note",
                  "age_warning_message": ""
              }
             
          ]
      },
      {
          "category_id": 67,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 100,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:40:00",
          "display_at": "2022-02-13T11:40:00.000Z",
          "category_description_id": 38,
          "lang_code": "vn",
          "category": "Laptop",
          "description": "Laptop",
          "meta_keywords": "Bán lẻ Laptop chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Laptop",
          "page_title": "Laptop",
          "age_warning_message": "",
          "children": []
      },
      {
          "category_id": 68,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 100,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:40:22",
          "display_at": "2022-02-13T11:40:22.000Z",
          "category_description_id": 39,
          "lang_code": "vn",
          "category": "Đồng hồ",
          "description": "Đồng hồ",
          "meta_keywords": "Bán lẻ Đồng hồ chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Đồng hồ",
          "page_title": "Đồng hồ",
          "age_warning_message": "",
          "children": []
      },
      {
          "category_id": 69,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 100,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:40:49",
          "display_at": "2022-02-13T11:40:49.000Z",
          "category_description_id": 40,
          "lang_code": "en",
          "category": "Phụ kiện",
          "description": "Phụ kiện điện thoại, laptop",
          "meta_keywords": "Bán lẻ Phụ kiện chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Phụ kiện",
          "page_title": "Phụ kiện",
          "age_warning_message": "",
          "children": []
      },
      {
          "category_id": 70,
          "parent_id": 0,
          "id_path": "0",
          "level": 1,
          "company_id": 0,
          "usergroup_ids": "23",
          "status": "A",
          "product_count": 100,
          "position": 0,
          "is_op": "N",
          "localization": "vn",
          "age_verification": "N",
          "age_limit": 0,
          "parent_age_verification": "N",
          "parent_age_limit": 0,
          "selected_views": "",
          "default_view": "",
          "product_details_view": "",
          "product_columns": 0,
          "is_trash": "N",
          "category_type": "C",
          "created_at": "2022-02-13 18:41:16",
          "display_at": "2022-02-13T11:41:16.000Z",
          "category_description_id": 41,
          "lang_code": "vn",
          "category": "Máy cũ",
          "description": "Máy cũ",
          "meta_keywords": "Bán lẻ Máy cũ chính hãng giá rẻ so với thị trường : Samsung, Xíaomi, Oppo..., có đủ dòng điện thoại cũ đã qua sử dụng trên thị trường Di động Việt tại TPHCM, Cần Thơ, Đà Nẵng",
          "meta_description": "Máy cũ",
          "page_title": "Máy cũ",
          "age_warning_message": "",
          "children": []
      }
  ],
  "message": "",
  "timestamp": "17/02/2022, 14:25:08"
}