export default {
	FETCH_ATTRIBUTES_LIST_START: "FETCH_ATTRIBUTES_LIST_START",
	FETCH_ATTRIBUTES_LIST_SUCCESS: "FETCH_ATTRIBUTES_LIST_SUCCESS",
	FETCH_ATTRIBUTES_LIST_FAILURE: "FETCH_ATTRIBUTES_LIST_FAILURE",

	GET_ATTRIBUTE_BY_ID_START: "GET_ATTRIBUTE_BY_ID_START",
	GET_ATTRIBUTE_BY_ID_SUCCESS: "GET_ATTRIBUTE_BY_ID_SUCCESS",
	GET_ATTRIBUTE_BY_ID_FAILURE: "GET_ATTRIBUTE_BY_ID_FAILURE",

	UPDATE_ATTRIBUTE_START: "UPDATE_ATTRIBUTE_START",
	UPDATE_ATTRIBUTE_SUCCESS: "UPDATE_ATTRIBUTE_SUCCESS",
	UPDATE_ATTRIBUTE_FAILURE: "UPDATE_ATTRIBUTE_FAILURE",

	CREATE_ATTRIBUTE_START: "CREATE_ATTRIBUTE_START",
	CREATE_ATTRIBUTE_SUCCESS: "CREATE_ATTRIBUTE_SUCCESS",
	CREATE_ATTRIBUTE_FAILURE: "CREATE_ATTRIBUTE_FAILURE",

	UPDATE_ATTRIBUTE_STATUS_START: "UPDATE_ATTRIBUTE_STATUS_START",
	UPDATE_ATTRIBUTE_STATUS_SUCCESS: "UPDATE_ATTRIBUTE_STATUS_SUCCESS",
	UPDATE_ATTRIBUTE_STATUS_FAILURE: "UPDATE_ATTRIBUTE_STATUS_FAILURE",

	START_ADD_CATEGORY_FEATURES: "START_ADD_CATEGORY_FEATURES",
	ADD_CATEGORY_FEATURES_SUCCESS: "ADD_CATEGORY_FEATURES_SUCCESS",
	ADD_CATEGORY_FEATURES_FAILURE: "ADD_CATEGORY_FEATURES_FAILURE"
};
