const billsTypes = {
	START_GET_LIST_BILL: "START_GET_LIST_BILL",
	GET_LIST_BILL_SUCCESS: "GET_LIST_BILL_SUCCESS",
	GET_LIST_BILL_FAILURE: "GET_LIST_BILL_FAILURE",

	START_GET_BILL_BY_ID: "START_GET_BILL_BY_ID",
	GET_BILL_BY_ID_SUCCESS: "GET_BILL_BY_ID_SUCCESS",
	GET_BILL_BY_ID_FAILURE: "GET_BILL_BY_ID_FAILURE"
};

export default billsTypes;
