const catalogsTypes = {
	START_GET_LIST_CATALOGS: "START_GET_LIST_CATALOGS",
	GET_LIST_CATALOGS_SUCCESS: "START_GET_LIST_CATALOGS_SUCCESS",
	GET_LIST_CATALOGS_FAILURE: "START_GET_LIST_CATALOGS_FAILURE",

	START_CREATE_CATALOGS: "START_CREATE_CATALOGS",
	CREATE_CATALOGS_SUCCESS: "CREATE_CATALOGS_SUCCESS",
	CREATE_CATALOGS_FAILURE: "CREATE_CATALOGS_FAILURE",

	START_UPDATE_CATALOGS: "START_UPDATE_CATALOGS",
	UPDATE_CATALOGS_SUCCESS: "UPDATE_CATALOGS_SUCCESS",
	UPDATE_CATALOGS_FAILURE: "UPDATE_CATALOGS_FAILURE",

	START_GET_CATALOGS_BY_ID: "START_GET_CATALOGS_BY_ID",
	GET_CATALOGS_BY_ID_SUCCESS: "GET_CATALOGS_BY_ID_SUCCESS",
	GET_CATALOGS_BY_ID_FAILURE: "GET_CATALOGS_BY_ID_FAILURE",

	START_UPDATE_STATUS_CATEGORY_CATALOGS: "START_UPDATE_STATUS_CATEGORY_CATALOGS",
	UPDATE_STATUS_CATEGORY_CATALOGS_SUCCESS: "UPDATE_STATUS_CATEGORY_CATALOGS_SUCCESS",
	UPDATE_STATUS_CATEGORY_CATALOGS_FAILURE: "UPDATE_STATUS_CATEGORY_CATALOGS_FAILURE",

	START_UPDATE_INDEX_CATALOG: "START_UPDATE_INDEX_CATALOG",
	UPDATE_INDEX_CATALOG_SUCCESS: "UPDATE_INDEX_CATALOG_SUCCESS",
	UPDATE_INDEX_CATALOG_FAILURE: "UPDATE_INDEX_CATALOG_FAILURE"
};
export default catalogsTypes;
