const categoryTypes = {
	START_GET_LIST_CATEGORY: "START_GET_LIST_CATEGORY",
	GET_LIST_CATEGORY_SUCCESS: "GET_LIST_CATEGORY_SUCCESS",
	GET_LIST_CATEGORY_FAILURE: "GET_LIST_CATEGORY_FAILURE",

	START_UPDATE_CATEGORY: "START_UPDATE_CATEGORY",
	UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
	UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

	START_CREATE_CATEGORY: "START_CREATE_CATEGORY",
	CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
	CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

	START_UPDATE_INDEX_CATEGORY: "START_UPDATE_INDEX_CATEGORY",
	UPDATE_INDEX_CATEGORY_SUCCESS: "UPDATE_INDEX_CATEGORY_SUCCESS",
	UPDATE_INDEX_CATEGORY_FAILURE: "UPDATE_INDEX_CATEGORY_FAILURE",

	START_GET_CATEGORY_BY_ID: "START_GET_CATEGORY_BY_ID",
	GET_CATEGORY_BY_ID_SUCCESS: "GET_CATEGORY_BY_ID_SUCCESS",
	GET_CATEGORY_BY_ID_FAILURE: "GET_CATEGORY_BY_ID_FAILURE",

	START_UPDATE_PRODUCT_IN_CATEGORY: "START_UPDATE_PRODUCT_IN_CATEGORY",
	UPDATE_PRODUCT_IN_CATEGORY_SUCCESS: "UPDATE_PRODUCT_IN_CATEGORY_SUCCESS",
	UPDATE_PRODUCT_IN_CATEGORY_FAILURE: "UPDATE_PRODUCT_IN_CATEGORY_FAILURE"
};

export default categoryTypes;
