const codTypes = {
	START_GET_LIST_COD: "START_GET_LIST_COD",
	GET_LIST_COD_SUCCESS: "GET_LIST_COD_SUCCESS",
	GET_LIST_COD_FAILURE: "GET_LIST_COD_FAILURE",

	START_CREATE_COD: "START_CREATE_COD",
	CREATE_COD_SUCCESS: "CREATE_COD_SUCCESS",
	CREATE_COD_FAILURE: "CREATE_COD_FAILURE",

	START_UPDATE_COD: "START_UPDATE_COD",
	UPDATE_COD_SUCCESS: "UPDATE_COD_SUCCESS",
	UPDATE_COD_FAILURE: "UPDATE_COD_FAILURE",

	START_GET_COD_BY_ID: "START_GET_COD_BY_ID",
	GET_COD_BY_ID_SUCCESS: "GET_COD_BY_ID_SUCCESS",
	GET_COD_BY_ID_FAILURE: "GET_COD_BY_ID_FAILURE"

	// START_UPDATE_INDEX_CATALOG: "START_UPDATE_INDEX_CATALOG",
	// UPDATE_INDEX_CATALOG_SUCCESS: "UPDATE_INDEX_CATALOG_SUCCESS",
	// UPDATE_INDEX_CATALOG_FAILURE: "UPDATE_INDEX_CATALOG_FAILURE"
};
export default codTypes;
