const configsTypes = {
	START_GET_LIST_CONFIGS: "START_GET_LIST_CONFIGS",
	GET_LIST_CONFIGS_SUCCESS: "GET_LIST_CONFIGS_SUCCESS",
	GET_LIST_CONFIGS_FAILURE: "GET_LIST_CONFIGS_FAILURE",

	START_CREATE_CONFIGS: "START_CREATE_CONFIGS",
	CREATE_CONFIGS_SUCCESS: "CREATE_CONFIGS_SUCCESS",
	CREATE_CONFIGS_FAILURE: "CREATE_CONFIGS_FAILURE",

	START_UPDATE_CONFIGS: "START_UPDATE_CONFIGS",
	UPDATE_CONFIGS_SUCCESS: "UPDATE_CONFIGS_SUCCESS",
	UPDATE_CONFIGS_FAILURE: "UPDATE_CONFIGS_FAILURE",

	START_GET_CONFIGS_BY_ID: "START_GET_CONFIGS_BY_ID",
	GET_CONFIGS_BY_ID_SUCCESS: "GET_CONFIGS_BY_ID_SUCCESS",
	GET_CONFIGS_BY_ID_FAILURE: "GET_CONFIGS_BY_ID_FAILURE"
};
export default configsTypes;
