const inventoryTypes = {
	START_GET_LIST_INVENTORY: "START_GET_LIST_INVENTORY",
	GET_LIST_INVENTORY_SUCCESS: "START_GET_LIST_INVENTORY_SUCCESS",
	GET_LIST_INVENTORY_FAILURE: "START_GET_LIST_INVENTORY_FAILURE",

	START_CREATE_INVENTORY: "START_CREATE_INVENTORY",
	CREATE_INVENTORY_SUCCESS: "CREATE_INVENTORY_SUCCESS",
	CREATE_INVENTORY_FAILURE: "CREATE_INVENTORY_FAILURE",

	START_UPDATE_INVENTORY: "START_UPDATE_INVENTORY",
	UPDATE_INVENTORY_SUCCESS: "UPDATE_INVENTORY_SUCCESS",
	UPDATE_INVENTORY_FAILURE: "UPDATE_INVENTORY_FAILURE",

	START_GET_INVENTORY_BY_ID: "START_GET_INVENTORY_BY_ID",
	GET_INVENTORY_BY_ID_SUCCESS: "GET_INVENTORY_BY_ID_SUCCESS",
	GET_INVENTORY_BY_ID_FAILURE: "GET_INVENTORY_BY_ID_FAILURE",

	START_UPDATE_STATUS_CATEGORY_CATALOGS: "START_UPDATE_STATUS_CATEGORY_CATALOGS",
	UPDATE_STATUS_CATEGORY_CATALOGS_SUCCESS: "UPDATE_STATUS_CATEGORY_CATALOGS_SUCCESS",
	UPDATE_STATUS_CATEGORY_CATALOGS_FAILURE: "UPDATE_STATUS_CATEGORY_CATALOGS_FAILURE"

	// START_UPDATE_INDEX_CATALOG: "START_UPDATE_INDEX_CATALOG",
	// UPDATE_INDEX_CATALOG_SUCCESS: "UPDATE_INDEX_CATALOG_SUCCESS",
	// UPDATE_INDEX_CATALOG_FAILURE: "UPDATE_INDEX_CATALOG_FAILURE"
};
export default inventoryTypes;
