const packagesTypes = {
	START_GET_LIST_PACKAGES: "START_GET_LIST_PACKAGES",
	GET_LIST_PACKAGES_SUCCESS: "START_GET_LIST_PACKAGES_SUCCESS",
	GET_LIST_PACKAGES_FAILURE: "START_GET_LIST_PACKAGES_FAILURE",

	START_CREATE_PACKAGES: "START_CREATE_PACKAGES",
	CREATE_PACKAGES_SUCCESS: "CREATE_PACKAGES_SUCCESS",
	CREATE_PACKAGES_FAILURE: "CREATE_PACKAGES_FAILURE",

	START_UPDATE_PACKAGES: "START_UPDATE_PACKAGES",
	UPDATE_PACKAGES_SUCCESS: "UPDATE_PACKAGES_SUCCESS",
	UPDATE_PACKAGES_FAILURE: "UPDATE_PACKAGES_FAILURE",

	START_GET_PACKAGES_BY_ID: "START_GET_PACKAGES_BY_ID",
	GET_PACKAGES_BY_ID_SUCCESS: "GET_PACKAGES_BY_ID_SUCCESS",
	GET_PACKAGES_BY_ID_FAILURE: "GET_PACKAGES_BY_ID_FAILURE"
};
export default packagesTypes;
