const productTypes = {
	CREATE_PRODUCT_START: "CREATE_PRODUCT_START",
	CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
	CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",

	FETCH_PRODUCTS_LIST_START: "FETCH_PRODUCTS_LIST_START",
	FETCH_PRODUCTS_LIST_SUCCESS: "FETCH_PRODUCTS_LIST_SUCCESS",
	FETCH_PRODUCTS_LIST_FAILURE: "FETCH_PRODUCTS_LIST_FAILURE",

	START_GET_PRODUCT_BY_ID: "START_GET_PRODUCT_BY_ID",
	GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
	GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

	START_UPDATE_PRODUCT_BY_ID: "START_UPDATE_PRODUCT_BY_ID",
	UPDATE_PRODUCT_BY_ID_SUCCESS: "UPDATE_PRODUCT_BY_ID_SUCCESS",
	UPDATE_PRODUCT_BY_ID_FAILURE: "UPDATE_PRODUCT_BY_ID_FAILURE",

	START_GET_PRODUCT_LOGS: "START_GET_PRODUCT_LOGS",
	GET_PRODUCT_LOGS_SUCCESS: "GET_PRODUCT_LOGS_SUCCESS",
	GET_PRODUCT_LOGS_FAILURE: "GET_PRODUCT_LOGS_FAILURE"
};

export default productTypes;
